### PR TITLE
create a program to evaluate the detector parameters

### PR DESCRIPTION
**Pull request by gustavoneves12**
create a program to evaluate the detector parameters.

### CODE REVIEW

**Comment by gustavoneves12** [comment]
[Acoustic Target Tracking: Tunning Jequitaia/Balsa Detector](https://trello.com/c/Z8I8Z4aq/22-acoustic-target-tracking-tunning-jequitaia-balsa-detector)

**Comment by gustavoneves12** [comment]
I performed some tests and I get the following error: 

```
OpenCV Error: Assertion failed (points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S)) in minAreaRect, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/imgproc/src/contours.cpp, line 1913
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/imgproc/src/contours.cpp:1913: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function minAreaRect
```

**Comment by gustavoneves12** [comment]
The error above mentioned was fix in the commit: https://github.com/sonar-data-processing/sonarlog_target_tracking/pull/1/commits/7507cd27d28b3326e6ef9c78668f283e8917f02a

**Comment by trocolit2** [comment]
Looks fine for me!
Feel free to merge.

**Pull request merged**
